-- 1. Crear tabla de historial si no existe
create table if not exists public.p2p_rate_history (
  id bigint generated by default as identity primary key,
  price numeric not null,
  details jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar seguridad (Row Level Security)
alter table public.p2p_rate_history enable row level security;

-- 3. Permitir lectura publica (para que la App pueda mostrar la grafica)
create policy "Allow public read access" 
on public.p2p_rate_history 
for select 
to public 
using (true);

-- 4. Permitir escritura solo al sistema/service_role (para que la Edge Function pueda guardar datos)
create policy "Allow service_role insert" 
on public.p2p_rate_history 
for insert 
to service_role 
with check (true);
