-- Create table for storing BCV rates history
CREATE TABLE IF NOT EXISTS public.bcv_rates_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    usd DECIMAL(10, 8) NOT NULL,
    eur DECIMAL(10, 8) NOT NULL,
    source TEXT DEFAULT 'bcv-scraper',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add unique constraint on date to ensure one record per day
ALTER TABLE public.bcv_rates_history 
ADD CONSTRAINT bcv_rates_history_date_key UNIQUE (date);

-- Enable Row Level Security (RLS)
ALTER TABLE public.bcv_rates_history ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public read access
CREATE POLICY "Allow public read access"
ON public.bcv_rates_history
FOR SELECT
TO anon, authenticated
USING (true);

-- Create policy to allow service role (Edge Functions) to insert/update
CREATE POLICY "Allow service role full access"
ON public.bcv_rates_history
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
